
project_id = "csilkrfizphtbmevlkme"

[functions.linkedin-connect]
verify_jwt = true

[functions.linkedin-webhook]
verify_jwt = false

[functions.apify-webhook]
verify_jwt = false

[functions.process-linkedin-post]
verify_jwt = false

[functions.apify-client-jobs-webhook]
verify_jwt = false
