// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csilkrfizphtbmevlkme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzaWxrcmZpenBodGJtZXZsa21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzE3MjksImV4cCI6MjA2Mzg0NzcyOX0.4jzjSkQVa1COccnCtdar3PkOnBBhX5xHRul1qk7Zbls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);